In [1]:
import numpy as np

### 1. Create a 3x3x3 array with random values

In [2]:
a = np.random.randint(0, 100, (3,3,3))
a

array([[[16, 85, 79],
        [30, 97, 80],
        [95,  2, 96]],

       [[80,  6, 79],
        [25, 78, 42],
        [40, 69, 49]],

       [[16,  1, 95],
        [92,  0, 40],
        [93, 73, 99]]])

### 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a = np.zeros((5,5))
a = np.diag(np.arange(1,5), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
# Lets assume 1 to be black colored cell a 0 to be white colored
a = np.ones((8,8))
a[1::2, ::2] = 0 # a[1,0] then step of 2
a[::2, 1::2] = 0 # a[0,1] then step of 2
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### 4. Normalize a 5x5 random matrix

In [5]:
a = np.random.random((3,3))
print("Original Matrix")
print(a)
amax, amin = a.max(), a.min()
a = (a - amin) / (amax - amin)
print("After Normalization")
print(a)

Original Matrix
[[0.87045345 0.1191315  0.39317284]
 [0.90629905 0.23913812 0.70531329]
 [0.8495504  0.94382077 0.03379121]]
After Normalization
[[0.91937919 0.09377749 0.39491204]
 [0.95876867 0.22564861 0.73791238]
 [0.89640954 1.         0.        ]]


### 5. How to find common values between two arrays?

In [6]:
a = np.arange(1,10)
b = np.arange(4,14)
print(np.intersect1d(a, b))

[4 5 6 7 8 9]


### 6. How to get the dates of yesterday, todat and tomorrow?

In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


### 7. Consider two random array A and B, check if they are equal

In [8]:
a = np.random.random(10)
b = np.random.random(10)
print(np.array_equal(a, b))

False


### 8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
a = np.random.random(10)
print(a)
print()
a[a.argmax()] = 0
print(a)

[0.70407027 0.53432882 0.83710148 0.91695098 0.49980131 0.87033959
 0.90544528 0.68078508 0.50252902 0.737099  ]

[0.70407027 0.53432882 0.83710148 0.         0.49980131 0.87033959
 0.90544528 0.68078508 0.50252902 0.737099  ]


### 9. How to print all the values of an array?

In [10]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


### 10. Subtract the mean of each row of a matrix

In [11]:
a = np.random.randint(1,10,(3,3))
print(a)
print(a - a.mean(axis = 0))


[[5 5 5]
 [1 4 9]
 [2 5 3]]
[[ 2.33333333  0.33333333 -0.66666667]
 [-1.66666667 -0.66666667  3.33333333]
 [-0.66666667  0.33333333 -2.66666667]]


### 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
a = np.random.randint(1,5,10)
print(a)
b = np.arange(0,10)
print(b)
a[b] += 1
print(a)

[2 2 4 4 4 1 2 3 2 2]
[0 1 2 3 4 5 6 7 8 9]
[3 3 5 5 5 2 3 4 3 3]


### 12. How to get the diagonal of a dot product?

In [13]:
a = np.random.random((3,3))
b = np.random.random((3,3))
print(np.diag(np.dot(a, b)))

[0.13284986 0.34562344 0.8039955 ]


### 13. How to find the most frequent value in an array?

In [14]:
a = np.random.randint(0,10,100)
print(a)
print(np.bincount(a).argmax())

[2 6 3 8 2 7 3 3 5 8 4 9 9 9 0 4 1 2 2 5 6 7 5 1 0 0 9 7 8 2 4 3 1 4 1 7 4
 6 8 5 3 0 2 4 0 8 4 0 4 0 4 6 9 6 5 1 4 5 0 1 6 0 4 0 8 8 9 1 6 1 6 2 6 4
 9 4 2 9 6 3 0 7 9 2 1 5 1 5 6 3 2 4 7 2 9 5 6 0 9 7]
4


### 14. How to get the n largest values of an array

In [15]:
a = np.arange(0,20)
print(a)
n = 3
print(a[np.argsort(a)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[17 18 19]


### 15. How to create a record array from a regular array?

In [16]:
a = np.array([1,2,3])
b = np.array(['Sky', 'Earth', 'Water'])
c = np.array(['Blue', 'Brown', 'Blue'])
record = np.core.records.fromarrays([a,b,c], names = 'x,y,z')
print(record)

[(1, 'Sky', 'Blue') (2, 'Earth', 'Brown') (3, 'Water', 'Blue')]
